# Generated by Django 6.1.2 on 2026-10-06 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name="titre de l'événement")),
                ('message', models.TextField(blank=True, verbose_name="message d'invitation")),
                ('event_date', models.DateField(verbose_name="date de l'événement")),
                ('event_time', models.TimeField(verbose_name="heure de l'événement")),
                ('timezone', models.CharField(default='Africa/Kinshasa', max_length=64, verbose_name='fuseau horaire')),
                ('venue_name', models.CharField(blank=True, max_length=200, verbose_name='lieu')),
                ('venue_address', models.CharField(blank=True, max_length=255, verbose_name='adresse')),
                ('venue_details', models.TextField(blank=True, verbose_name='précisions sur le lieu')),
                ('cover_image', models.ImageField(blank=True, upload_to='covers/%Y/%m/', verbose_name='image de couverture')),
                ('display_config', models.JSONField(blank=True, default=dict, verbose_name='mise en forme')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_models', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_models', to='templates_app.invitationtemplate')),
            ],
            options={
                'verbose_name': "modèle d'événement",
                'verbose_name_plural': "modèles d'événements",
                'ordering': ('-event_date', '-created_at'),
                'indexes': [models.Index(fields=['organizer', 'event_date'], name='events_even_organiz_b2856f_idx')],
            },
        ),
    ]
