# Generated by Django 6.1.2 on 2026-10-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='message_font',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='police du message'),
        ),
    ]
