# Generated by Django 6.1.2 on 2026-10-07 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_eventmodel_message_font'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='font_size',
            field=models.CharField(blank=True, default='', max_length=32, verbose_name='taille du texte'),
        ),
    ]
