# Generated by Django 6.1.2 on 2026-10-08 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_eventmodel_font_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='DressCodeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='dress_code/%Y/%m/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='légende')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dress_code_images', to='events.eventmodel')),
            ],
            options={
                'verbose_name': 'image du code vestimentaire',
                'verbose_name_plural': 'images du code vestimentaire',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='ProgramItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='heure de début')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='heure de fin')),
                ('description', models.CharField(max_length=255, verbose_name='description')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_items', to='events.eventmodel')),
            ],
            options={
                'verbose_name': 'étape du programme',
                'verbose_name_plural': 'étapes du programme',
                'ordering': ('order', 'id'),
            },
        ),
    ]
