# Generated by Django 6.1.2 on 2026-10-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_dresscodeimage_programitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='cover_title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='texte de couverture'),
        ),
    ]
