# Generated by Django 6.1.2 on 2026-10-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvitationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True, verbose_name='identifiant')),
                ('name', models.CharField(max_length=120, verbose_name='nom')),
                ('category', models.CharField(choices=[('wedding', 'Mariage'), ('birthday', 'Anniversaire'), ('graduation', 'Remise de diplômes'), ('reception', 'Réception / cérémonie'), ('anniversary', 'Anniversaire de mariage'), ('memorial', 'Hommage'), ('corporate', 'Entreprise'), ('other', 'Autre')], default='other', max_length=32, verbose_name='catégorie')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='capacités')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "modèle d'invitation",
                'verbose_name_plural': "modèles d'invitation",
                'ordering': ('category', 'name'),
            },
        ),
    ]
