# Generated by Django 6.1.2 on 2026-10-06 18:40

import django.db.models.deletion
import django.utils.timezone
import invitations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guest_name', models.CharField(max_length=200, verbose_name="nom de l'invité")),
                ('civility', models.CharField(choices=[('none', '—'), ('m', 'M.'), ('mme', 'Mme'), ('mlle', 'Mlle'), ('couple', 'M. & Mme')], default='none', max_length=16, verbose_name='civilité')),
                ('token', models.CharField(default=invitations.models.generate_invitation_token, editable=False, max_length=64, unique=True, verbose_name='jeton public')),
                ('state', models.CharField(choices=[('active', 'Active'), ('revoked', 'Révoquée'), ('expired', 'Expirée'), ('deleted', 'Supprimée')], default='active', max_length=16, verbose_name='état')),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='émise le')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expire le')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='révoquée le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='events.eventmodel')),
            ],
            options={
                'verbose_name': 'invitation',
                'verbose_name_plural': 'invitations',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['event_model', 'state'], name='invitations_event_m_8550c7_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_at__isnull', True), ('expires_at__gt', models.F('issued_at')), _connector='OR'), name='invitation_expiry_after_issue')],
            },
        ),
    ]
