# Generated by Django 6.1.2 on 2026-10-06 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference_response', to='invitations.invitation')),
            ],
            options={
                'verbose_name': "réponse d'invité",
                'verbose_name_plural': "réponses d'invités",
                'ordering': ('-submitted_at',),
            },
        ),
        migrations.CreateModel(
            name='PreferenceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='question')),
                ('help_text', models.CharField(blank=True, max_length=255, verbose_name='précision')),
                ('input_type', models.CharField(choices=[('single', 'Choix unique'), ('multiple', 'Choix multiples')], default='single', max_length=16, verbose_name='type')),
                ('required', models.BooleanField(default=False, verbose_name='obligatoire')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('event_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preference_questions', to='events.eventmodel')),
            ],
            options={
                'verbose_name': 'question de préférence',
                'verbose_name_plural': 'questions de préférence',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PreferenceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='option')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ordre')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='preferences.preferencequestion')),
            ],
            options={
                'verbose_name': 'option de préférence',
                'verbose_name_plural': 'options de préférence',
                'ordering': ('order', 'id'),
            },
        ),
        migrations.CreateModel(
            name='GuestResponseAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='preferences.guestresponse')),
                ('options', models.ManyToManyField(related_name='answers', to='preferences.preferenceoption')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='preferences.preferencequestion')),
            ],
            options={
                'verbose_name': 'réponse à une question',
                'verbose_name_plural': 'réponses aux questions',
                'constraints': [models.UniqueConstraint(fields=('response', 'question'), name='unique_answer_per_question')],
            },
        ),
    ]
