# Generated by Django 6.1.2 on 2026-10-06 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(db_index=True, max_length=64, verbose_name='action')),
                ('target_type', models.CharField(blank=True, max_length=64, verbose_name='ressource')),
                ('target_id', models.CharField(blank=True, max_length=64, verbose_name='identifiant')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='détails')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "journal d'activité",
                'verbose_name_plural': "journal d'activité",
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['target_type', 'target_id'], name='core_activi_target__d3fcab_idx')],
            },
        ),
    ]
